--SESION 3 =======================================================================
--942,401

SELECT TOP 10000 * FROM CLIENTES


SELECT SEXO , COUNT(*) CANT
FROM CLIENTES
WHERE NOMBRE IS NOT NULL
GROUP BY SEXO
HAVING COUNT(*) > 16000
ORDER BY CANT DESC

------ CUANTOS CLIENTES TIENEN COMO NOMBRE MARCELO

SELECT COUNT(*) AS cantidad_clientes
FROM CLIENTES
WHERE NOMBRE LIKE 'Marcelo'

select COUNT (*)
from clientes
where nombre= 'MARCELO'


select COUNT(*) nombre
from CLIENTES
where nombre='Marcelo'

DELETE
FROM CLIENTES
WHERE nombre='Marcelo'

--SELECT * 
--INTO Z_CLIENTES
--FROM CLIENTES


--SELECT * FROM CLIENTES

SELECT DISTINCT NOMBRE
FROM CLIENTES


--------DELETE
DELETE   CLIENTES
WHERE NUMDOC = '01544354' AND id = 320081

DELETE FROM CLIENTES
WHERE NUMDOC = '01544354' AND id = 320081

DELETE A
FROM CLIENTES A
WHERE NUMDOC = '01544354' AND id = 320081

SELECT *
FROM CLIENTES
WHERE NUMDOC = '01544354' AND id = 320081


---- CON VALORES MANUALES
-- VALUES()
-----A TRAVES DE UNA CONSULTA

--------------------------
--CREATE TABLE ALUMNOS_G19 (NOMBRE VARCHAR(50) , APELLIDO VARCHAR(100) , EMAIL VARCHAR(100))

INSERT INTO ALUMNOS_G19
	(nombre, apellido)
---NOMINAL TIENE TARGET
VALUES
	('NIXON3', 'LLANOS' ),
	('NIXON4', 'LLANOS' )

INSERT INTO ALUMNOS_G19
	(NOMBRE , APELLIDO)
SELECT NOMBRE , apellidoPaterno
FROM CLIENTES
WHERE NOMBRE IS NOT NULL

--SELECT * FROM ALUMNOS_G19

insert into clientes
select *
from Z_CLIENTES
where nombre = 'Marcelo'


UPDATE ALUMNOS_G19 SET EMAIL = null
--WHERE EMAIL = 'generico2@gmail.com'

--SELECT * FROM ALUMNOS_G19
--WHERE EMAIL IS NULL


SELECT COUNT(*)
FROM OFERTAS
WHERE LINEA >1000

SELECT COUNT(*)
FROM OFERTAS
WHERE LINEA <1000

SELECT COUNT(*)
FROM OFERTAS
WHERE LINEA  = 1000

SELECT COUNT(*)
FROM OFERTAS
WHERE LINEA  <> 1000

SELECT COUNT(*)
FROM OFERTAS
WHERE LINEA  != 1000

SELECT COUNT(*)
FROM OFERTAS
WHERE LINEA >= 1000

SELECT *
FROM OFERTAS
WHERE LINEA <= 1000

SELECT COUNT(*)
FROM OFERTAS
WHERE LINEA >=1000 AND LINEA <=5000

SELECT COUNT(*)
FROM OFERTAS
WHERE LINEA BETWEEN 1000 AND  5000


SELECT *
FROM AGENCIAS
WHERE AGENCIA IN ('AG. AREQUIPA','AG. CAJAMARCA','AG. CUSCO')


SELECT *
FROM AGENCIAS
WHERE AGENCIA IN (SELECT AGENCIA FROM COLABORADORES WHERE CODIGO_TRABAJADOR = '10001')


--% = PORCENTAJE , NO TIENE UN LARGO DEFINIDO
--_ = GUION BAJO , TIENE UN LARGO DEFINIDO


SELECT *
FROM CLIENTES
WHERE NOMBRE LIKE 'CLA%'

SELECT *
FROM CLIENTES
WHERE NOMBRE LIKE '%DIA'

SELECT *
FROM CLIENTES
WHERE NOMBRE LIKE 'CL%IA'

SELECT *
FROM CLIENTES
WHERE NOMBRE LIKE 'CLA____'

SELECT *
FROM CLIENTES
WHERE NOMBRE LIKE '____DIA'

SELECT *
FROM CLIENTES
WHERE NOMBRE LIKE 'CL___IA'

------REGULAR EXPRESION

--------IS NULL

--NULL

SELECT *
FROM OFERTAS
WHERE LINEA = NULL

SELECT *
FROM OFERTAS
WHERE LINEA IS NULL



SELECT 'HOLA MUNDO' + ISNULL(NULL,' QUE TAL')
---  identifica si el valor es nulo y cambia el valor por uno especifico


SELECT 'HOLA MUNDO' + NULLIF('HOLA' ,'HOLA' )
--- cambia de valor a null si encuentra un valor especifico
SELECT 'HOLA MUNDO' + NULL


SELECT top  1
	'el producto es:' +   nullif (codigo_producto,'PLD')
FROM OFERTAS
where  codigo_producto  != 'pld'
SELECT top  1
	'el producto es:' +   nullif (codigo_producto,'PLD')
FROM OFERTAS
where  codigo_producto  = 'pld'


select top 1
	'el producto es:'  + nullif(codigo_producto,'PLD')
from ofertas
where codigo_producto  = 'pld'
select top 1
	'el producto es:'  + nullif(codigo_producto,'PLD')
from ofertas
where codigo_producto  != 'pld'


select 1000/nullif(0,0)

------concat
select concat(
	'hola mundo',
	cast(1 as varchar)
)


--CONDICION 1 AND CONDICION 2 
--CONDICION 1 OR CONDICION 2
-- NOT (CONDICION 1)

------operaciones entre condiciones AND OR NOT

SELECT TOP 100
	*
FROM OFERTAS
WHERE LINEA <5000 AND tasa > 20
-- AND .... AND


SELECT TOP 100
	*
FROM OFERTAS
WHERE LINEA <5000 OR tasa > 20
-- OR .... OR ... OR


SELECT TOP 100
	*
FROM OFERTAS
WHERE NOT(LINEA <5000)

SELECT TOP 100
	*
FROM OFERTAS
WHERE NOT(LINEA =5000)


SELECT TOP 100
	*
FROM OFERTAS
WHERE (LINEA <5000 AND tasa > 20)
-- OR .... OR

SELECT TOP 100
	*
FROM OFERTAS
WHERE (LINEA <5000 OR tasa > 20)
-- AND ....   ... AND
